{
  imports = [
    ./ayu.nix
    ./onedark.nix
    ./onelight.nix
    ./dracula.nix
    ./material.nix
    ./palenight.nix
    ./nightfox.nix
    ./kanagawa.nix
    ./rose-pine.nix
    ./monokai.nix
    ./solarized.nix
    ./everforest.nix
    ./gruvbox.nix
    ./catppuccin.nix
    ./nord.nix
    ./tokyonight.nix
  ];
}
